name: Deploy to VPS
on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deployment repo
        uses: actions/checkout@v4

      - name: Upload deployment files
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{secrets.VP_HOST}}
          username: ${{secrets.VP_USER}}
          key: ${{secrets.SSH_KEY}}
          source: "deploy/*"
          target: "/opt/blog-platform"

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{secrets.VP_HOST}}
          username: ${{secrets.VP_USER}}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd /opt/blog-platform
            docker compose -f docker-compose.prod.yml --env-file .env.prod pull
            docker compose -f docker-compose.prod.yml --env-file .env.prod up -d